export const nounSuffixes = [
  "ing",
  "ment",
  "tion",
  "ness",
  "ity",
  "ance",
  "ence",
  "al",
  "er",
  "ism",
  "ist",
  "ity",
  "ment",
  "or",
  "ship",
  "sion",
  "tude",
  "age",
  "dom",
  "ee",
  "ery",
  "hood",
  "ment",
  "ness",
  "ry",
  "th",
];

export const properNouns = [
  "i",
  "alice",
  "bob",
  "charlie",
  "david",
  "eve",
  "frank",
  "grace",
  "heidi",
  "ivan",
  "judy",
  "kevin",
  "larry",
  "mallory",
  "nancy",
  "oscar",
  "peggy",
  "quentin",
  "romeo",
  "sue",
  "trent",
  "ursula",
  "victor",
  "walter",
  "xander",
  "yvonne",
  "zelda",
  "abe",
  "belle",
  "clyde",
  "dora",
  "ed",
  "faye",
  "gus",
  "holly",
  "aberdeen",
  "baltimore",
  "cleveland",
  "denver",
  "eugene",
  "fargo",
  "gainesville",
  "harrisburg",
  "alabama",
  "alaska",
  "arizona",
  "arkansas",
  "california",
  "colorado",
  "connecticut",
  "delaware",
  "florida",
  "georgia",
  "hawaii",
  "alberta",
  "british columbia",
  "manitoba",
  "new brunswick",
  "india",
  "united kingdom",
  "united states",
  "new zealand",
  "france",
  "oman",
  "tunisia",
  "spain",
  "türkiye",
  "sweden",
  "australia",
  "austria",
  "albania",
  "pakistan",
  "french polynesia",
  "denmark",
  "ghana",
  "uzbekistan",
  "switzerland",
  "taiwan",
  "poland",
  "romania",
  "yemen",
  "nepal",
  "brazil",
  "namibia",
  "cambodia",
  "tanzania",
  "guernsey",
  "turkmenistan",
  "kyrgyzstan",
  "kazakhstan",
  "canada",
  "south korea",
  "liberia",
  "sri lanka",
  "kuwait",
  "russia",
  "indonesia",
  "morocco",
  "saudi arabia",
  "afghanistan",
  "argentina",
  "vietnam",
  "greece",
  "honduras",
  "mauritius",
  "malta",
  "united arab emirates",
  "finland",
  "germany",
  "china",
  "maldives",
  "singapore",
  "malaysia",
  "thailand",
  "algeria",
  "armenia",
  "bangladesh",
  "belgium",
  "ecuador",
  "philippines",
  "japan",
  "portugal",
  "italy",
  "hungary",
  "croatia",
  "south africa",
  "norway",
  "guatemala",
  "u.s. virgin islands",
  "montenegro",
  "åland islands",
  "american samoa",
  "andorra",
  "angola",
  "anguilla",
  "antarctica",
  "antigua and barbuda",
  "aruba",
  "azerbaijan",
  "the bahamas",
  "bahrain",
  "barbados",
  "belarus",
  "belize",
  "benin",
  "bermuda",
  "bhutan",
  "bolivia",
  "bosnia and herzegovina",
  "botswana",
  "british indian ocean territory",
  "brunei",
  "bulgaria",
  "burkina faso",
  "burundi",
  "cameroon",
  "cabo verde",
  "cayman islands",
  "central african republic",
  "chad",
  "chile",
  "christmas island",
  "cocos (keeling) islands",
  "colombia",
  "comoros",
  "republic of the congo",
  "democratic republic of the congo",
  "cook islands",
  "costa rica",
  "côte d'ivoire",
  "cuba",
  "cyprus",
  "czechia",
  "djibouti",
  "dominica",
  "dominican republic",
  "egypt",
  "el salvador",
  "equatorial guinea",
  "eritrea",
  "estonia",
  "ethiopia",
  "falkland islands (islas malvinas)",
  "faroe islands",
  "fiji",
  "french guiana",
  "gabon",
  "the gambia",
  "georgia",
  "gibraltar",
  "greenland",
  "grenada",
  "guadeloupe",
  "guam",
  "guinea",
  "guinea-bissau",
  "guyana",
  "haiti",
  "vatican city",
  "hong kong",
  "iceland",
  "iran",
  "mauritania",
  "iraq",
  "ireland",
  "isle of man",
  "israel",
  "jamaica",
  "jersey",
  "jordan",
  "kenya",
  "kiribati",
  "laos",
  "latvia",
  "lebanon",
  "lesotho",
  "libya",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "macao",
  "north macedonia",
  "madagascar",
  "malawi",
  "mali",
  "marshall islands",
  "martinique",
  "mayotte",
  "mexico",
  "micronesia",
  "moldova",
  "monaco",
  "zimbabwe",
  "zambia",
  "mongolia",
  "wallis and futuna",
  "montserrat",
  "british virgin islands",
  "mozambique",
  "venezuela",
  "myanmar (burma)",
  "nauru",
  "vanuatu",
  "netherlands",
  "uruguay",
  "new caledonia",
  "nicaragua",
  "niger",
  "nigeria",
  "ukraine",
  "niue",
  "norfolk island",
  "uganda",
  "northern mariana islands",
  "tuvalu",
  "palau",
  "palestine",
  "panama",
  "papua new guinea",
  "paraguay",
  "peru",
  "pitcairn islands",
  "puerto rico",
  "trinidad and tobago",
  "qatar",
  "tonga",
  "tokelau",
  "rwanda",
  "togo",
  "réunion",
  "timor-leste",
  "tajikistan",
  "syria",
  "eswatini",
  "svalbard and jan mayen",
  "suriname",
  "sudan",
  "south georgia and the south sandwich islands",
  "south sudan",
  "somalia",
  "solomon islands",
  "slovenia",
  "slovakia",
  "sierra leone",
  "seychelles",
  "serbia",
  "senegal",
  "são tomé and príncipe",
  "san marino",
  "samoa",
  "saint martin",
  "saint vincent and the grenadines",
  "saint pierre and miquelon",
  "saint lucia",
  "saint barthélemy",
  "saint kitts and nevis",
  "saint helena, ascension and tristan da cunha",
  "turks and caicos islands",
];
